# Site settings
title: Ole Vik
email: git@olevik.net
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Ole Vik.
baseurl: ""
url: "http://olevik.me"

# Build settings
markdown: kramdown
mode: production